import Foundation
import CryptoKit
import CommonCrypto
import Security

/// Errors from `EncryptedFileCredentialStore`.
///
/// `wrongPassphrase` covers both "the passphrase is actually wrong" and
/// "the ciphertext was tampered with" — AES-GCM authentication failure
/// can't distinguish the two, and it must not distinguish them: either way
/// the caller must not receive plaintext.
enum EncryptedStoreError: Error, LocalizedError, Equatable {
    /// No key is currently held in memory — `unlock`/`createStore` must be
    /// called first. Distinct from "no secret stored" so callers never
    /// silently treat "locked" as "nothing saved" (see `CredentialStore`
    /// doc comment and ConnectionManager's ISSUE-016 history).
    case locked
    /// GCM authentication failed while decrypting: wrong passphrase, or the
    /// persisted file was tampered with. Never surfaces as plaintext.
    case wrongPassphrase
    /// `createStore` was called but a store file already exists.
    case alreadyExists
    /// `unlock` was called but no store file exists yet — the caller should
    /// offer `createStore` instead.
    case storeNotFound
    /// The persisted file exists but is not a well-formed envelope (bad
    /// JSON, unsupported version/kdf, implausible field), independent of
    /// the passphrase.
    case corruptStore(String)
    /// Filesystem-level failure (permissions, disk full, rename failed…).
    case ioError(String)

    var errorDescription: String? {
        switch self {
        case .locked:
            return "The encrypted credential store is locked. Unlock it with your passphrase first."
        case .wrongPassphrase:
            return "Incorrect passphrase."
        case .alreadyExists:
            return "An encrypted credential store already exists at this location."
        case .storeNotFound:
            return "No encrypted credential store exists yet. Create one first."
        case .corruptStore(let reason):
            return "Encrypted credential store is corrupt: \(reason)"
        case .ioError(let reason):
            return "Encrypted credential store I/O error: \(reason)"
        }
    }
}

/// A `CredentialStore` backed by a single AES-256-GCM-encrypted JSON file,
/// unlocked with a user-chosen passphrase. Depends on no OS keychain
/// service, so it works unchanged on a future Linux/Windows port — the
/// third option (alongside `NullCredentialStore` and `KeychainStore`) that
/// lets VNC/RDP profiles have a saved password without tying RemminaMac to
/// Apple Keychain.
///
/// ## Cryptographic design
/// - Key derivation: PBKDF2-HMAC-SHA256 (CommonCrypto `CCKeyDerivationPBKDF`),
///   600,000 iterations (OWASP 2023 guidance), 32-byte output, 32-byte
///   random salt (`SecRandomCopyBytes`) generated once at store creation and
///   stored in the file header.
/// - Cipher: AES-256-GCM (CryptoKit). A fresh random nonce is generated by
///   CryptoKit for every single `seal` call (`AES.GCM.seal(_:using:)`) and
///   persisted alongside the ciphertext — nonces are never reused with the
///   same key.
/// - The entire secrets dictionary is encrypted as one blob (not per-entry),
///   so the file leaks neither how many credentials exist nor their order.
///
/// ## Unlock model
/// The derived key lives in memory only (`keyBox`, guarded by `lock`), for
/// the lifetime of the store instance / app run. Nothing persists it to
/// disk. While locked, `secret(_:for:)` throws `.locked` rather than
/// returning `nil` — returning `nil` while locked would look identical to
/// "no password saved" and let the app silently connect with no
/// credential, which is exactly the bug class ISSUE-016 was about.
final class EncryptedFileCredentialStore: CredentialStore {
    /// Production singleton, targeting `~/Library/Application
    /// Support/RemminaMac/credentials.enc`. Deliberately a singleton (unlike
    /// `KeychainStore()`, which is stateless and safe to reconstruct per
    /// call): this store's derived key lives in an in-memory box tied to
    /// the instance, so a fresh instance per call would make the store
    /// perpetually re-lock itself between operations.
    static let shared = EncryptedFileCredentialStore(directory: EncryptedFileCredentialStore.defaultDirectory())

    static let pbkdf2Iterations = 600_000
    static let saltLength = 32
    static let keyLength = 32
    static let nonceLength = 12
    /// Upper bound sanity check on an iteration count read back from a
    /// persisted file's (unauthenticated) header — guards against a
    /// corrupted or hostile header causing a multi-minute PBKDF2 hang.
    static let maxPlausibleIterations = 5_000_000

    private let directoryURL: URL
    let fileURL: URL

    /// Holds the derived key. A separate reference type (rather than a
    /// `var` directly on `EncryptedFileCredentialStore`) so the store
    /// itself keeps only `let` stored properties and can conform to
    /// `Sendable` without `@unchecked` — every access to `key` goes through
    /// `lock`.
    private final class KeyBox: @unchecked Sendable {
        var key: SymmetricKey?
    }
    private let keyBox = KeyBox()
    private let stateLock = NSLock()

    /// - Parameter directory: directory containing `credentials.enc`.
    ///   Tests pass a per-test temporary directory so they never touch the
    ///   real `~/Library/Application Support/RemminaMac/`. Does NOT touch
    ///   the filesystem — directory creation happens lazily in
    ///   `createStore`/`save`, not here, so constructing (or merely reading
    ///   `displayName`/`persists` on) an instance is free of I/O side
    ///   effects.
    init(directory: URL) {
        self.directoryURL = directory
        self.fileURL = directory.appendingPathComponent("credentials.enc")
    }

    static func defaultDirectory() -> URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support")
        return base.appendingPathComponent("RemminaMac", isDirectory: true)
    }

    // MARK: - CredentialStore

    var persists: Bool { true }
    var displayName: String { "Encrypted file (portable)" }

    // MARK: - Unlock model

    var isUnlocked: Bool {
        stateLock.lock(); defer { stateLock.unlock() }
        return keyBox.key != nil
    }

    /// Whether a store file already exists on disk (used by the UI to
    /// decide between the "Create" and "Unlock" flows).
    var fileExists: Bool {
        FileManager.default.fileExists(atPath: fileURL.path)
    }

    /// Initializes a new, empty encrypted file protected by `passphrase`.
    /// Throws `.alreadyExists` if a store file is already present — this
    /// never overwrites an existing store.
    func createStore(withPassphrase passphrase: String) throws {
        guard !fileExists else { throw EncryptedStoreError.alreadyExists }

        var saltBytes = [UInt8](repeating: 0, count: Self.saltLength)
        let status = SecRandomCopyBytes(kSecRandomDefault, saltBytes.count, &saltBytes)
        guard status == errSecSuccess else {
            throw EncryptedStoreError.ioError("SecRandomCopyBytes failed with status \(status)")
        }
        let salt = Data(saltBytes)

        let key = try Self.deriveKey(passphrase: passphrase, salt: salt, iterations: Self.pbkdf2Iterations)
        try writeEnvelope(secrets: [:], key: key, salt: salt, iterations: Self.pbkdf2Iterations)

        stateLock.lock()
        keyBox.key = key
        stateLock.unlock()
    }

    /// Derives the key from `passphrase` and the persisted salt, then
    /// attempts to decrypt the store to validate it. Throws
    /// `.wrongPassphrase` (never returns with a "successfully unlocked but
    /// empty" state) if GCM authentication fails.
    func unlock(withPassphrase passphrase: String) throws {
        guard fileExists else { throw EncryptedStoreError.storeNotFound }

        let envelope = try readEnvelope()
        try Self.validate(envelope)

        guard let salt = Data(base64Encoded: envelope.salt) else {
            throw EncryptedStoreError.corruptStore("salt is not valid base64")
        }
        let key = try Self.deriveKey(passphrase: passphrase, salt: salt, iterations: envelope.iterations)

        // Validate the passphrase by actually decrypting — never mark the
        // store unlocked on an unverified key.
        _ = try Self.decrypt(envelope: envelope, key: key)

        stateLock.lock()
        keyBox.key = key
        stateLock.unlock()
    }

    /// Drops the derived key from memory. Nothing else changes on disk.
    func lock() {
        stateLock.lock()
        keyBox.key = nil
        stateLock.unlock()
    }

    func secret(_ kind: SecretKind, for profileId: UUID) throws -> String? {
        guard let key = currentKey() else { throw EncryptedStoreError.locked }
        let envelope = try readEnvelope()
        let dict = try Self.decrypt(envelope: envelope, key: key)
        return dict[storageKey(kind, profileId)]
    }

    func save(_ secret: String, kind: SecretKind, for profileId: UUID) throws {
        try mutate { dict in
            dict[self.storageKey(kind, profileId)] = secret
        }
    }

    func delete(_ kind: SecretKind, for profileId: UUID) throws {
        try mutate { dict in
            dict.removeValue(forKey: self.storageKey(kind, profileId))
        }
    }

    func deleteAll(for profileId: UUID) throws {
        let prefix = "\(profileId.uuidString)."
        try mutate { dict in
            for key in dict.keys where key.hasPrefix(prefix) {
                dict.removeValue(forKey: key)
            }
        }
    }

    // MARK: - Internals

    private func storageKey(_ kind: SecretKind, _ profileId: UUID) -> String {
        "\(profileId.uuidString).\(kind.storageKey)"
    }

    private func currentKey() -> SymmetricKey? {
        stateLock.lock(); defer { stateLock.unlock() }
        return keyBox.key
    }

    /// Read-decrypt-modify-encrypt-write, holding no plaintext dictionary
    /// beyond the scope of this call.
    private func mutate(_ body: (inout [String: String]) -> Void) throws {
        guard let key = currentKey() else { throw EncryptedStoreError.locked }
        let envelope = try readEnvelope()
        var dict = try Self.decrypt(envelope: envelope, key: key)
        body(&dict)
        guard let salt = Data(base64Encoded: envelope.salt) else {
            throw EncryptedStoreError.corruptStore("salt is not valid base64")
        }
        try writeEnvelope(secrets: dict, key: key, salt: salt, iterations: envelope.iterations)
    }

    // MARK: - Envelope (file format)

    /// `{ "version": 1, "kdf": "PBKDF2-HMAC-SHA256", "iterations": 600000,
    ///   "salt": "<base64>", "nonce": "<base64>", "ciphertext": "<base64>" }`
    /// `ciphertext` here is CryptoKit's `ciphertext || tag` (GCM's 16-byte
    /// authentication tag appended) — `nonce` is stored separately per spec,
    /// even though it is also recoverable from `AES.GCM.SealedBox.combined`.
    struct Envelope: Codable {
        var version: Int
        var kdf: String
        var iterations: Int
        var salt: String
        var nonce: String
        var ciphertext: String
    }

    static let kdfIdentifier = "PBKDF2-HMAC-SHA256"

    private static func validate(_ envelope: Envelope) throws {
        guard envelope.version == 1 else {
            throw EncryptedStoreError.corruptStore("unsupported envelope version \(envelope.version)")
        }
        guard envelope.kdf == kdfIdentifier else {
            throw EncryptedStoreError.corruptStore("unsupported KDF \(envelope.kdf)")
        }
        guard envelope.iterations > 0, envelope.iterations <= maxPlausibleIterations else {
            throw EncryptedStoreError.corruptStore("implausible iteration count \(envelope.iterations)")
        }
    }

    private func readEnvelope() throws -> Envelope {
        guard let data = FileManager.default.contents(atPath: fileURL.path) else {
            throw EncryptedStoreError.storeNotFound
        }
        do {
            return try JSONDecoder().decode(Envelope.self, from: data)
        } catch {
            throw EncryptedStoreError.corruptStore("envelope is not valid JSON")
        }
    }

    private func writeEnvelope(secrets: [String: String], key: SymmetricKey, salt: Data, iterations: Int) throws {
        let plaintext: Data
        do {
            plaintext = try JSONEncoder().encode(secrets)
        } catch {
            throw EncryptedStoreError.ioError("failed to encode secrets dictionary")
        }

        // Fresh random nonce every single seal — CryptoKit generates this
        // internally; we never supply or reuse one.
        let sealed: AES.GCM.SealedBox
        do {
            sealed = try AES.GCM.seal(plaintext, using: key)
        } catch {
            throw EncryptedStoreError.ioError("AES-GCM seal failed")
        }

        let envelope = Envelope(
            version: 1,
            kdf: Self.kdfIdentifier,
            iterations: iterations,
            salt: salt.base64EncodedString(),
            nonce: Data(sealed.nonce).base64EncodedString(),
            ciphertext: (sealed.ciphertext + sealed.tag).base64EncodedString()
        )

        let envelopeData: Data
        do {
            envelopeData = try JSONEncoder().encode(envelope)
        } catch {
            throw EncryptedStoreError.ioError("failed to encode envelope")
        }

        try Self.atomicWrite(envelopeData, to: fileURL)
    }

    private static func decrypt(envelope: Envelope, key: SymmetricKey) throws -> [String: String] {
        guard let nonceData = Data(base64Encoded: envelope.nonce),
              nonceData.count == nonceLength else {
            throw EncryptedStoreError.corruptStore("nonce is not valid base64 of the expected length")
        }
        guard let cipherAndTag = Data(base64Encoded: envelope.ciphertext),
              cipherAndTag.count >= 16 else {
            throw EncryptedStoreError.corruptStore("ciphertext is not valid base64 / too short")
        }

        let nonce: AES.GCM.Nonce
        let sealedBox: AES.GCM.SealedBox
        do {
            nonce = try AES.GCM.Nonce(data: nonceData)
            sealedBox = try AES.GCM.SealedBox(combined: Data(nonce) + cipherAndTag)
        } catch {
            throw EncryptedStoreError.corruptStore("malformed sealed box")
        }

        let plaintext: Data
        do {
            plaintext = try AES.GCM.open(sealedBox, using: key)
        } catch {
            // CryptoKitError.authenticationFailure: wrong key OR tampered
            // ciphertext. GCM cannot and must not distinguish the two —
            // either way this must never surface as plaintext.
            throw EncryptedStoreError.wrongPassphrase
        }

        do {
            return try JSONDecoder().decode([String: String].self, from: plaintext)
        } catch {
            // Authentication succeeded (so the key is right and the bytes
            // are untampered) but the payload wasn't the expected JSON
            // shape — a corrupt-but-correctly-keyed store, not a wrong
            // passphrase.
            throw EncryptedStoreError.corruptStore("decrypted payload was not the expected JSON shape")
        }
    }

    // MARK: - Key derivation

    private static func deriveKey(passphrase: String, salt: Data, iterations: Int) throws -> SymmetricKey {
        var derived = [UInt8](repeating: 0, count: keyLength)
        let saltBytes = [UInt8](salt)

        let status = passphrase.withCString { passPtr -> Int32 in
            saltBytes.withUnsafeBufferPointer { saltBuf -> Int32 in
                derived.withUnsafeMutableBufferPointer { derivedBuf -> Int32 in
                    CCKeyDerivationPBKDF(
                        CCPBKDFAlgorithm(kCCPBKDF2),
                        passPtr,
                        strlen(passPtr),
                        saltBuf.baseAddress,
                        saltBuf.count,
                        CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA256),
                        UInt32(iterations),
                        derivedBuf.baseAddress,
                        derivedBuf.count
                    )
                }
            }
        }

        guard status == kCCSuccess else {
            throw EncryptedStoreError.ioError("PBKDF2 key derivation failed with status \(status)")
        }

        let key = SymmetricKey(data: derived)
        // Defense in depth: overwrite the local copy now that CryptoKit has
        // its own copy inside SymmetricKey. Does not guarantee the backing
        // memory of every intermediate copy is zeroed (Swift makes no such
        // promise for Array/String), but it's better than leaving it be.
        for i in derived.indices { derived[i] = 0 }
        return key
    }

    // MARK: - Atomic, permission-safe writes

    /// Writes `data` to a temp file (mode 0600, verified) in the same
    /// directory as `url`, then `rename`s it over `url`. A crash mid-write
    /// leaves at most the untouched original file or an orphaned temp file
    /// — never a truncated/corrupt `url`.
    private static func atomicWrite(_ data: Data, to url: URL) throws {
        let fm = FileManager.default
        let dir = url.deletingLastPathComponent()
        do {
            try fm.createDirectory(at: dir, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        } catch {
            throw EncryptedStoreError.ioError("failed to create directory \(dir.path)")
        }

        let tempURL = dir.appendingPathComponent(".\(url.lastPathComponent).tmp-\(UUID().uuidString)")

        let fd = tempURL.path.withCString { open($0, O_CREAT | O_EXCL | O_WRONLY, 0o600) }
        guard fd >= 0 else {
            throw EncryptedStoreError.ioError("open(O_CREAT|O_EXCL) failed: \(String(cString: strerror(errno)))")
        }

        var failure: EncryptedStoreError?

        let written = data.withUnsafeBytes { (ptr: UnsafeRawBufferPointer) -> Int in
            write(fd, ptr.baseAddress, ptr.count)
        }
        if written != data.count {
            failure = .ioError("short write (\(written)/\(data.count) bytes)")
        }

        if failure == nil {
            var st = stat()
            if fstat(fd, &st) != 0 {
                failure = .ioError("fstat failed: \(String(cString: strerror(errno)))")
            } else if (st.st_mode & 0o777) != 0o600 {
                failure = .ioError("temp file mode is \(String((st.st_mode & 0o777), radix: 8)), expected 600")
            }
        }

        fsync(fd)
        close(fd)

        if let failure {
            try? fm.removeItem(at: tempURL)
            throw failure
        }

        guard rename(tempURL.path, url.path) == 0 else {
            let renameError = EncryptedStoreError.ioError("rename failed: \(String(cString: strerror(errno)))")
            try? fm.removeItem(at: tempURL)
            throw renameError
        }
    }
}
